algorithm: mvc
seed: 1
train_data:
  graph_generator: ba
  graph_generator_kwargs:
    M_range: [1, 10]
  node_samples:
    16: 1000
  num_envs: 4
  seed: 0
  graph_dir: graph_data
val_data:
  graph_generator: ba
  graph_generator_kwargs:
    M_range: [1, 10]
  node_samples:
    16: 100
  deterministic: true
  num_envs: 4
  seed: 1
  graph_dir: graph_data
test_data:
  graph_generator: ba
  graph_generator_kwargs:
    M_range: [1, 10]
  node_samples:
    16: 100
    32: 100
    64: 100
    128: 100
    256: 100
    512: 100
    1024: 100
  deterministic: true
  num_envs: 1
  seed: 2
  graph_dir: graph_data
policy_kwargs:
  embed_dim: 64
  pooling_type: max
  network_kwargs:
    network: MPNN
    aggr: sum
    num_gnn_layers: 4
    num_mlp_layers: 2
BC:
  n_episodes: 10000
  n_epochs: 10
  learning_rate: 0.001
  batch_size: 32
  vf_coef: 0
  gamma: 1
  seed: 17
  eval_freq: 100
weights_init:
  gnn_init: sparse
  encoder_init: ibarz2022
