algorithm: rgc
seed: 1
env_kwargs:
  objective_method: targeted
expert_policy_kwargs:
  method: greedy
  objective: targeted
train_data:
  graph_generator: ba
  graph_generator_kwargs:
    M: 2
    tau: 0.05
  node_samples:
    20: 10000
  num_envs: 4
  seed: 42
  graph_dir: graph_data
val_data:
  graph_generator: ba
  graph_generator_kwargs:
    M: 2
    tau: 0.05
  node_samples:
    20: 100
  deterministic: true
  num_envs: 4
  seed: 80085
  graph_dir: graph_data
test_data:
  graph_generator: ba
  graph_generator_kwargs:
    M: 2
    tau: 0.05
  node_samples:
    20: 100
    40: 100
    60: 100
    80: 100
    100: 100
  deterministic: true
  num_envs: 4
  seed: 42069
  graph_dir: graph_data
policy_kwargs:
  embed_dim: 64
  pooling_type: max
  network_kwargs:
    network: MPNN
    aggr: sum
    num_gnn_layers: 4
    num_mlp_layers: 3
PPO:
  n_steps: 1024
  n_epochs: 10
  gamma: 1
  learning_rate: 0.0005
  timesteps: 10000000
  batch_size: 128
  seed: 8
  eval_freq: 1024
BC:
  n_episodes: 10000
  n_epochs: 1
  learning_rate: 0.0005
  batch_size: 8
  vf_coef: 0.005
  gamma: 1
  seed: 17
  eval_freq: 100
weights_init:
  gnn_init: sparse
  encoder_init: ibarz2022
